version: '3.7'
services:
  django:
    restart: always
    build:
      context: ./django
      args:
        - POSTGRES_PASSWORD
    expose:
      - 3031
    depends_on:
      - postgres
    command: bash -c "python manage.py migrate && gunicorn weather_forecast_api.wsgi -b 0.0.0.0:3031"
    volumes:
      - "staticdata:/opt/static/"
    environment:
      - POSTGRES_PASSWORD
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - $NGINX_PORT:80
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"
  postgres:
    image: postgres
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD

volumes:
  dbdata:
  staticdata:

