version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - $MYSQL_PORT:3306
    volumes:
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ
    restart: always
  django:
    build: ./django
    expose:
      - 3031
    depends_on:
      - db
    command: bash -c "python manage.py migrate && gunicorn ${DJANGO_PROJECT_NAME}.wsgi -b 0.0.0.0:3031"
    volumes:
      - ./django/apps:/opt/apps/
      - ./staticdata:/opt/static/
    environment:
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ
      - DARKSKY_API_KEY
    restart: always
  nginx:
    image: nginx
    depends_on:
      - django
    ports:
      - $NGINX_PORT:80
    volumes:
      - ./nginx/:/etc/nginx/
      - ./staticdata:/opt/apps/static/
    restart: always

