# Generated by Django 3.0.3 on 2020-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_subdivisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='local_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='local_name',
            field=models.CharField(max_length=16),
        ),
    ]
