# Generated by Django 3.0.3 on 2020-03-30 00:32

import os
from django.core.management import call_command
from django.db import migrations


APP_LABEL = 'manage_subdivisions'


def load_fixture(apps, schema_editor):
    fixture_dir = os.path.join(APP_LABEL, 'fixture')
    call_command('loaddata', os.path.join(fixture_dir, 'subdivision.json'), app_label=APP_LABEL)
    call_command('loaddata', os.path.join(fixture_dir, 'city.json'), app_label=APP_LABEL)


class Migration(migrations.Migration):

    dependencies = [
        (APP_LABEL, '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
